[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
    let g:jedi#use_tabs_not_buffers = 1
    let g:jedi#popup_select_first = 0
    let g:jedi#popup_on_dot = 0 
    let g:jedi#completions_command = "<TAB>"
    let g:jedi#goto_command = "<C-d>"
    let g:jedi#got_assignments_command = "<C-g>"
    let g:jedi#goto_definitions_command = "<C-d>"
    let g:jedi#documentation_command = "<C-k>"
    let g:jedi#usages_command = "<C-n>"
    let g:jedi#rename_command = "<C-r>"
    autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'ervandew/supertab'
